server:
  port: ${SPRING_BACKEND_PORT}
spring:
  datasource:
    postgres:
      url: ${DATABASE_URL}
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
orders:
  shipping-orders-update-enabled: ${SHIPPING_ORDERS_UPDATE_ENABLED}